version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./src/:/var/www/html
     ports:
       - "${WORDPRESS_PORT}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
       WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
       WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
       WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
       WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
       WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
       WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
       WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
       WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
       WORDPRESS_DEBUG_MODE: ${WORDPRESS_DEBUG_MODE}

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - "85:80"
     links:
       - db:db

   composer:
     image: composer
     working_dir: /var/www/html
     volumes:
       - ./src:/var/www/html

volumes:
    db_data: {}
